"""empty message

Revision ID: 39a05ef06b60
Revises: 
Create Date: 2020-04-09 12:37:08.387629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a05ef06b60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('alipay_id', sa.String(length=32), nullable=True),
    sa.Column('wechat_id', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('_password', sa.String(length=256), nullable=True),
    sa.Column('invest_id', sa.String(length=16), nullable=True),
    sa.Column('is_wechat', sa.Boolean(), nullable=True),
    sa.Column('is_taobao', sa.Boolean(), nullable=True),
    sa.Column('permission', sa.Integer(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alipay_id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('wechat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
